Implementasi Jaringan Syaraf Tiruan: Menentukan jumlah produksi di perusahaan berdasarkan tingkat permintaan dan persediaan

In [25]:
#import numpy
import numpy as np

In [102]:
#masukan input
#input 0 = produksi banyak (PB)
#input 1 = produksi kecil (PK)

#kombinasi input = 0,1 output 1
#kombinasi input = 1,2 output 0
#kombinasi input = 0,2 output 1

#output 0 = produksi besar
#output 1 = produksi kecil

#inputkan value
inputFeatures = np.array([[0,0],[0,1],[1,0],[1,1]])
targetOutput = np.array([[0],[0.3],[0.4],[1]])
weights = np.array([[0.1],[0.2]])

In [104]:
#input tipe produksi
produksiSedikit = 0
produksiBanyak = 1

In [123]:
#variabel input produksi simpan val
pManufactured= "MFD-210111"
pExpired= "EXP-240111"
Kategori = "PB"

In [124]:
#nilai bias diubah nol
bias = 0 

In [125]:
#set learning rate
lr = 2

In [126]:
#fungsi simgmoid
def sigmoid(x):
  return 1/(1+np.exp(-x))
  
#derivasi
def sigmoid_der(x):
  return sigmoid(x)*(1-sigmoid(x))


In [127]:
#mulai mengecek dari hasil input
def cekProduksi():
  if hasil2 < 0.1 :
    pManufactured = "MFD-210111"
    print(pManufactured)
    pExpired = "EXP-240111"
    print(pExpired)
    Kategori = "PK"
    print(Kategori)
    print("Perusahaan akan memproduksi sebanyak jumlah permintaan sebanyak <100pcs")
  elif hasil2 < 0.3 :
    pManufactured = "MFD-210211"
    print(pManufactured)
    pExpired = "EXP-240211"
    print(pExpired)
    Kategori = "PK"
    print(Kategori)
    print("Perusahaan akan memproduksi sebanyak jumlah permintaan sebanyak <500pcs")
  elif hasil2 <= 0.4 :
    pManufactured = "MFD-210311"
    print(pManufactured)
    pExpired = "EXP-240311"
    print(pExpired)
    Kategori = "PK"
    print(Kategori)
    print("Perusahaan akan memproduksi sebanyak jumlah permintaan sebanyak <800pcs")
  elif hasil2 >= 0.5 :
    pManufactured = "MFD-210411"
    print(pManufactured)
    pExpired = "EXP-240411"
    print(pExpired)
    Kategori = "PK"
    print(Kategori)
    print("Perusahaan akan memproduksi sebanyak jumlah permintaan sebanyak <1500pcs")
  elif hasil2 > 0.6 :
    pManufactured = "MFD-210511"
    print(pManufactured)
    pExpired = "EXP-240511"
    print(pExpired)
    Kategori = "PB"
    print(Kategori)
    print("Perusahaan akan memproduksi sebanyak jumlah permintaan sebanyak >4000pcs")
  elif hasil2 > 0.9 :
    pManufactured = "MFD-210611"
    print(pManufactured)
    pExpired = "Exp-240611"
    print(pExpired)
    Kategori = "PB"
    print(Kategori)
    print("Perusahaan akan memproduksi sebanyak jumlah permintaan sebanyak >10000pcs")
    



In [128]:
#set epoch
for epoch in range(10000):
  inputs = inputFeatures
  in_o = np.dot(inputs, weights) + bias
  out_o = sigmoid(in_o)
  error = out_o - targetOutput
  x = error.sum()

  derr_dout = error
  dout_din = sigmoid_der(out_o)
  deriv = derr_dout * dout_din

  inputs = inputFeatures.T
  deriv_final = np.dot(inputs, deriv)


  weights -= lr * deriv_final
  print(weights)

  for i in deriv:
    bias -= lr * i
  print(bias)


Streaming output truncated to the last 5000 lines.
 [7.78803794]]
[-8.63403861]
[[8.22983944]
 [7.78814894]]
[-8.63414976]
[[8.22995045]
 [7.78825994]]
[-8.6342609]
[[8.23006145]
 [7.78837092]]
[-8.63437202]
[[8.23017243]
 [7.78848189]]
[-8.63448313]
[[8.2302834 ]
 [7.78859284]]
[-8.63459423]
[[8.23039436]
 [7.78870379]]
[-8.63470532]
[[8.23050531]
 [7.78881472]]
[-8.6348164]
[[8.23061625]
 [7.78892564]]
[-8.63492746]
[[8.23072717]
 [7.78903655]]
[-8.63503851]
[[8.23083808]
 [7.78914744]]
[-8.63514955]
[[8.23094898]
 [7.78925833]]
[-8.63526058]
[[8.23105987]
 [7.7893692 ]]
[-8.63537159]
[[8.23117074]
 [7.78948006]]
[-8.63548259]
[[8.2312816]
 [7.7895909]]
[-8.63559358]
[[8.23139245]
 [7.78970174]]
[-8.63570456]
[[8.23150329]
 [7.78981256]]
[-8.63581552]
[[8.23161411]
 [7.78992337]]
[-8.63592648]
[[8.23172493]
 [7.79003416]]
[-8.63603742]
[[8.23183573]
 [7.79014495]]
[-8.63614834]
[[8.23194651]
 [7.79025572]]
[-8.63625926]
[[8.23205729]
 [7.79036648]]
[-8.63637016]
[[8.23216805]
 [7.790

In [139]:
#hasil prediksi
singlePoint = np.array([produksiSedikit, produksiBanyak])
hasil1 = np.dot(singlePoint, weights) + bias
hasil2 = sigmoid(hasil1)

print("Prediksi Penentuan Produksi Harian Periode November 2021")
harian = (int(input("Tanggal hari ini: ")))
print(harian, " November 2021", "\n")
print(hasil2)
print("Rincian kode produksi: ")
cekProduksi()

Prediksi Penentuan Produksi Harian Periode November 2021
Tanggal hari ini: 12
12  November 2021 

[0.30023001]
Rincian kode produksi: 
MFD-210311
EXP-240311
PK
Perusahaan akan memproduksi sebanyak jumlah permintaan sebanyak <800pcs
