In [ ]:
#import numpy
import numpy as np

In [ ]:
#masukan input
#input 0 = marah
#input 1 = waspada
#input 2 = diam

#kombinasi input = 0,1 output 1
#kombinasi input = 1,2 output 0
#kombinasi input = 0,2 output 1

#output 0 = hewan jinak
#output 1 = hewan buas

#inputkan value
inputFeatures = np.array([[0,0],[0,1],[1,0],[1,1]])
targetOutput = np.array([[0],[0.9],[0.9],[1]])
weights = np.array([[0.1],[0.2]])

In [ ]:
#input tipe binatang
reaksiMarah = 0
reaksiWaspada = 1
#reaksiDiam = 2

In [ ]:
#variabel input binatang simpan val
tipeBinatang = "B1"

In [ ]:
#nilai bias diubah nol
bias = 0 

In [ ]:
#set learning rate
lr = 2

In [ ]:
#fungsi sigmoid
def sigmoid(x):
  return 1/(1+np.exp(-x))
  
#derivasi
def sigmoid_der(x):
  return sigmoid(x)*(1-sigmoid(x))


In [ ]:
#mulai mengecek dari hasil input
def cekTipeBinatang():
  if hasil2 < 0.1 :
    tipeBinatang = "B1"
    print(tipeBinatang)
    print("Tipe binatang ini adalah Binatang Jinak")
  elif hasil2 < 0.4 :
    tipeBinatang = "B2"
    print(tipeBinatang)
    print("Tipe binatang ini adalah Binatang Jinak")
  elif hasil2 > 0.6 :
    tipeBinatang = "B3"
    print(tipeBinatang)
    print("Tipe binatang ini adalah Binatang Buas")
  elif hasil2 > 0.9 :
    tipeBinatang = "B4"
    print(tipeBinatang)
    print("Tipe binatang ini adalah Binatang Buas")
    



In [ ]:
#set epoch
for epoch in range(10000):
  inputs = inputFeatures
  in_o = np.dot(inputs, weights) + bias
  out_o = sigmoid(in_o)
  error = out_o - targetOutput
  x = error.sum()

  derr_dout = error
  dout_din = sigmoid_der(out_o)
  deriv = derr_dout * dout_din

  inputs = inputFeatures.T
  deriv_final = np.dot(inputs, deriv)


  weights -= lr * deriv_final
  print(weights)

  for i in deriv:
    bias -= lr * i
  print(bias)


Streaming output truncated to the last 5000 lines.
 [9.60475985]]
[-7.41020588]
[[9.6048617]
 [9.6048617]]
[-7.41030747]
[[9.60496355]
 [9.60496355]]
[-7.41040904]
[[9.60506538]
 [9.60506538]]
[-7.4105106]
[[9.60516721]
 [9.60516721]]
[-7.41061216]
[[9.60526902]
 [9.60526902]]
[-7.4107137]
[[9.60537082]
 [9.60537082]]
[-7.41081523]
[[9.60547261]
 [9.60547261]]
[-7.41091675]
[[9.6055744]
 [9.6055744]]
[-7.41101826]
[[9.60567617]
 [9.60567617]]
[-7.41111977]
[[9.60577793]
 [9.60577793]]
[-7.41122126]
[[9.60587968]
 [9.60587968]]
[-7.41132274]
[[9.60598142]
 [9.60598142]]
[-7.41142421]
[[9.60608315]
 [9.60608315]]
[-7.41152567]
[[9.60618487]
 [9.60618487]]
[-7.41162712]
[[9.60628658]
 [9.60628658]]
[-7.41172856]
[[9.60638828]
 [9.60638828]]
[-7.41182999]
[[9.60648997]
 [9.60648997]]
[-7.41193141]
[[9.60659165]
 [9.60659165]]
[-7.41203282]
[[9.60669332]
 [9.60669332]]
[-7.41213422]
[[9.60679498]
 [9.60679498]]
[-7.4122356]
[[9.60689663]
 [9.60689663]]
[-7.41233698]
[[9.60699826]
 [9.606998

In [ ]:
#cek hasil
singlePoint = np.array([reaksiMarah, reaksiWaspada])
hasil1 = np.dot(singlePoint, weights) + bias
hasil2 = sigmoid(hasil1)

print(hasil2)
print("Tipe golongan binatang: ")
cekTipeBinatang()

[0.89979422]
Tipe golongan binatang: 
B3
Tipe binatang ini adalah Binatang Buas
