In [ ]:
#import numpy
import numpy as np

In [ ]:
#masukan input
#input 0 = marah
#input 1 = waspada
#input 2 = diam
#input

#kombinasi input = 0,1 output 1
#kombinasi input = 1,2 output 0
#kombinasi input = 0,2 output 1

#output 0 = hewan jinak
#output 1 = hewan buas


#inputkan value
#inputFeatures = np.array([[0,0],[0,1],[0,2],[1,0],[1,1],[1,2],[2,0],[2,1],[2,2]])
inputFeatures = np.array([[0,0],[0,1],[1,0],[1,1]])
#targetOutput = np.array([[0],[1],[2]])
targetOutput = np.array([[0],[0.9],[0.9],[1]])
weights = np.array([[0.1],[0.2]])

In [ ]:
#input tipe binatang
reaksiMarah = 0
reaksiWaspada = 1
#reaksiDiam = 2

In [ ]:
#variabel input binatang simpan val
tipeBinatang = "B1"

In [ ]:
#nilai bias diubah nol
bias = 0 

In [ ]:
#set learning rate
lr = 2

In [ ]:
#fungsi simgmoid
def sigmoid(x):
  return 1/(1+np.exp(-x))
  
#derivasi
def sigmoid_der(x):
  return sigmoid(x)*(1-sigmoid(x))


In [ ]:
#mulai mengecek dari hasil input
def cekTipeBinatang():
  if hasil2 < 0.1 :
    tipeBinatang = "B1"
    print(tipeBinatang)
    print("Tipe binatang ini adalah Binatang Jinak")
  elif hasil2 < 0.4 :
    tipeBinatang = "B2"
    print(tipeBinatang)
    print("Tipe binatang ini adalah Binatang Jinak")
  elif hasil2 > 0.6 :
    tipeBinatang = "B3"
    print(tipeBinatang)
    print("Tipe binatang ini adalah Binatang Buas")
  elif hasil2 > 0.9 :
    tipeBinatang = "B4"
    print(tipeBinatang)
    print("Tipe binatang ini adalah Binatang Buas")
    



In [ ]:
#set epoch
for epoch in range(10000):
  inputs = inputFeatures
  in_o = np.dot(inputs, weights) + bias
  out_o = sigmoid(in_o)
  error = out_o - targetOutput
  x = error.sum()

  derr_dout = error
  dout_din = sigmoid_der(out_o)
  deriv = derr_dout * dout_din

  inputs = inputFeatures.T
  deriv_final = np.dot(inputs, deriv)


  weights -= lr * deriv_final
  print(weights)

  for i in deriv:
    bias -= lr * i
  print(bias)


Streaming output truncated to the last 5000 lines.
 [10.3535201]]
[-8.15756103]
[[10.35356833]
 [10.35356833]]
[-8.1576092]
[[10.35361656]
 [10.35361656]]
[-8.15765736]
[[10.35366479]
 [10.35366479]]
[-8.15770553]
[[10.35371301]
 [10.35371301]]
[-8.15775369]
[[10.35376124]
 [10.35376124]]
[-8.15780186]
[[10.35380946]
 [10.35380946]]
[-8.15785001]
[[10.35385767]
 [10.35385767]]
[-8.15789817]
[[10.35390589]
 [10.35390589]]
[-8.15794633]
[[10.3539541]
 [10.3539541]]
[-8.15799448]
[[10.35400231]
 [10.35400231]]
[-8.15804263]
[[10.35405052]
 [10.35405052]]
[-8.15809077]
[[10.35409873]
 [10.35409873]]
[-8.15813892]
[[10.35414693]
 [10.35414693]]
[-8.15818706]
[[10.35419513]
 [10.35419513]]
[-8.1582352]
[[10.35424333]
 [10.35424333]]
[-8.15828334]
[[10.35429153]
 [10.35429153]]
[-8.15833148]
[[10.35433972]
 [10.35433972]]
[-8.15837961]
[[10.35438791]
 [10.35438791]]
[-8.15842774]
[[10.3544361]
 [10.3544361]]
[-8.15847587]
[[10.35448429]
 [10.35448429]]
[-8.158524]
[[10.35453248]
 [10.35453248

In [ ]:
#hasil
singlePoint = np.array([binatang1, binatang2])
hasil1 = np.dot(singlePoint, weights) + bias
hasil2 = sigmoid(hasil1)

print(hasil2)
print("Tipe golongan binatang: ")
cekTipeBinatang()

[0.89989451]
Tipe golongan binatang: 
B3
Tipe binatang ini adalah Binatang Buas
